---
- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: check docker repository exist
  check_mode: no
  changed_when: false
  shell: "yum-config-manager dockerrepo | wc -L"
  register: docker_repository_check

- name: set up stable repository
  command: "yum-config-manager --add-repo {{docker_repo.url}}"
  become: true
  when: docker_repository_check.stdout == 0



